root = "."
tmp_dir = "tmp"

[build]
# 実行ファイルの出力さき
cmd = "go build -o ./tmp/main ./cmd/api"
# ビルドされたバイナリの場所
bin = "./tmp/main"
# 起動時のコマンド（環境変数をセット）
full_bin = "APP_ENV=dev ./tmp/main"
# 監視対象の拡張子
include_ext = ["go", "tpl", "tmpl", "html", "sql"]
# 無視するディレクトリ
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules", "migrations"]
# 変更があった時の遅延（ミリ秒）
delay = 1000
# エラー時に停止
stop_on_error = true
# ログファイル名
log = "air_errors.log"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true